[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RJP"
version = "0.0.1"
authors = [
  { name="John Cogburn, Ryan Moorgen, Payne Persons ", email="jcogburn3633@floridapol.edu" },
]
description = "a comprehensive interactive data analysis and modeling platform that enables users to seamlessly import, clean, visualize, analyze, and model data using scientific calculations and data visualization tools."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/RyanPlayz49/Project_SPIDAM"
Issues = "https://github.com/RyanPlayz49/Project_SPIDAM/issues"